# Setup
title           : Google Fonts
description     : "Online preview for Google Fonts."
keywords        : "google fonts online preview"
url             : http://lefoy.net/google-fonts/

author          : lefoy
name            : "lefoy"
website         : http://lefoy.net/

version         : 1.0.0
markdown        : redcarpet
highlighter     : pygments

github          : https://github.com/lefoy
repo            : https://github.com/lefoy/google-fonts

# Assets
sass:
  sass_dir: _scss
  style: :compressed
